### ISSUE TITLE
Error executing examples from site

### ISSUE THREAD

**Issue by abelsromero** [rpau/walkmod-core#15] opened 2015-08-25 09:18 UTC
Hi,

I'm trying the tool after some time and I find that some old examples seem to fail with the last version, or else, I'm missing something, that could be.

I downloaded version 1.3.0 from https://bitbucket.org/rpau/walkmod/downloads and I'm attempting execute the script example (http://walkmod.com/manual.html#script) but I get the following error:

```
 INFO [main] - Java version: 1.7.0
 INFO [main] - Java Home: C:\home\bin\jdk1.7.0_x64\jre
 INFO [main] - OS: Windows 7, Vesion: 6.1
--------------------------------------------------------------------------------
                     _    _       _ _   ___  ___          _
                    | |  | |     | | |  |  \/  |         | |
                    | |  | | __ _| | | _| .  . | ___   __| |
                    | |/\| |/ _` | | |/ / |\/| |/ _ \ / _` |
                    \  /\  / (_| | |   <| |  | | (_) | (_| |
                     \/  \/ \__,_|_|_|\_\_|  |_/\___/ \__,_|
--------------------------------------------------------------------------------
An open source tool to apply code conventions
version 1.2 - July 2015 -
--------------------------------------------------------------------------------
 INFO [main] - c:\home\data\github\gradle-walkmod-plugin\src\test\resources\walkmod.xml [ok]
:: loading settings :: url = file:/C:/home/bin/walkmod-1.3.0/config/ivysettings.xml
:: loading settings :: url = jar:file:/C:/home/bin/walkmod-1.3.0/lib/ivy-2.4.0-rc1.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: org.walkmod#walkmod-imports-cleaner-plugin-caller;working
        confs: [default]
        found org.walkmod#walkmod-imports-cleaner-plugin;2.0 in maven2
        found org.walkmod#javalang;3.2.0 in maven2
        [3.2.0] org.walkmod#javalang;[3.0.0, 4.0.0)
        found org.walkmod#merger;1.0.1 in maven2
        [1.0.1] org.walkmod#merger;[1.0.1, 2.0)
        found org.walkmod#walkmod-javalang-plugin;2.3.2 in maven2
        [2.3.2] org.walkmod#walkmod-javalang-plugin;[2.0, 3.0)
        found org.walkmod#javalang;4.2.2 in maven2
        [4.2.2] org.walkmod#javalang;[3.1.0, 5.0.0)
        found org.walkmod#javalang-compiler;2.1.0 in maven2
        [2.1.0] org.walkmod#javalang-compiler;[2.0.0, 3.0.0)
        found log4j#log4j;1.2.16 in maven2
        found org.walkmod#walkmod-java-formatter-plugin;2.2.0 in maven2
        [2.2.0] org.walkmod#walkmod-java-formatter-plugin;[2.0, 3.0)
        found org.walkmod#javalang;4.2.2 in maven2
        [4.2.2] org.walkmod#javalang;[4.1.0, 5.0.0)
        found org.eclipse.core#org.eclipse.core.contenttype;3.4.100 in maven2
        found org.eclipse.equinox#org.eclipse.equinox.preferences;3.4.1 in maven2
        found org.eclipse.equinox#org.eclipse.equinox.common;3.6.0 in maven2
        found org.eclipse.equinox#org.eclipse.equinox.registry;3.5.101 in maven2
        found org.eclipse.core#org.eclipse.core.expressions;3.4.300 in maven2
        found org.eclipse.core#org.eclipse.core.runtime;3.7.0 in maven2
        found org.eclipse.osgi#org.eclipse.osgi;3.7.1 in maven2
        found org.eclipse.core#org.eclipse.core.jobs;3.5.100 in maven2
        found org.eclipse.equinox#org.eclipse.equinox.app;1.3.100 in maven2
        found org.eclipse.core#org.eclipse.core.filesystem;1.3.100 in maven2
        found org.eclipse.core#org.eclipse.core.resources;3.7.100 in maven2
        found org.eclipse.jdt#org.eclipse.jdt.core;3.10.0 in maven2
        found org.eclipse.text#org.eclipse.text;3.5.101 in maven2
:: resolution report :: resolve 14353ms :: artifacts dl 56ms
        :: evicted modules:
        org.walkmod#javalang;3.2.0 by [org.walkmod#javalang;4.2.2] in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   21  |   6   |   0   |   1   ||   26  |   0   |
        ---------------------------------------------------------------------
 INFO [main] - ** THE TRANSFORMATION CHAIN clean STARTS **
--------------------------------------------------------------------------------
 INFO [main] - >> cosa.Person
 INFO [main] - TRANSFORMATION CHAIN FAILS

--------------------------------------------------------------------------------
 INFO [main] - Total time: 0,058 seconds
 INFO [main] - Finished at: Tue, 25 Aug 2015 11:07:12
 INFO [main] - Final memory: 207 M/ 244 M
--------------------------------------------------------------------------------
 INFO [main] - Please, see the walkmod log file for details
ERROR [main] - TRANSFORMATION CHAIN (clean) FAILS
An exeception has been produced during the walkmod:commons:import-cleaner transformation - org.walkmod.util.location.LocationImpl@48ab464e
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:260)
        at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:275)
        at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:42)
        at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
        at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:165)
        at org.walkmod.WalkModFacade.executeChainAdapter(WalkModFacade.java:642)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:269)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:181)
Caused by: java.lang.reflect.InvocationTargetException
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.walkmod.walkers.AbstractWalker.write(AbstractWalker.java:200)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.write(DefaultJavaWalker.java:257)
        at org.walkmod.walkers.AbstractWalker.writeAll(AbstractWalker.java:179)
        at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:171)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:329)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:127)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.accept(DefaultJavaWalker.java:74)
        ... 12 more
Caused by: java.lang.NullPointerException
        at org.walkmod.javalang.actions.ActionsApplier.setText(ActionsApplier.java:42)
        at org.walkmod.javaformatter.writers.EclipseWriter.getContent(EclipseWriter.java:229)
        at org.walkmod.writers.AbstractFileWriter.write(AbstractFileWriter.java:118)
        ... 23 more
```

I've tried several scripts and gthe cleaner plugin and the error is always the same. An empty file is created in the output folder, but nothins is written in.

**Comment by rpau** [comment] 2015-08-26 06:54
Hi Abel,

Thank you for reporting the issue. Sorry for my delayed response because I was working on changing the web page and include a new service (walkmodhub). I will take a look today, but this issue happens for one of the latest changes done in the javalang plugin.

Thank you again to report any problem that you find.

**Comment by abelsromero** [comment] 2015-08-26 07:00
> Sorry for my delayed response because I was working on changing the web page and include a new service (walkmodhub)

No problem, take your time.

**Comment by rpau** [comment] 2015-08-26 07:44
Hi Abel,

Looking the set of dependencies, you are using old versions. Are you executing walkmod offline?
For another hand, I that you are executing the imports cleaner and it is not the same example than 
http://walkmod.com/manual#script

Could you paste your exact configuration? 

If you are not offline, myy suggestion is to try removing the walkmod libraries from your local ivy repo send me the stacktrace again.

**Comment by abelsromero** [comment] 2015-08-26 08:24
> Looking the set of dependencies, you are using old versions (of the imported libraries e.g javalang.jar or walkmod-imports-cleaner-plugin). Are you executing walkmod offline?

Im online, I know because I had to fight with a horrible proxy just now ><

To clarify the issue, I just run 2 clean tests:

**Environment**
* OS: Windows 7, using Cygwin
* Walkmod: Just downloaded version 1.3.0 (walkmod-1.3.0-installer.zip), unziped and set PATH variable, nothing else.
* Configuration: 2 chains, one with the cleaner plugin and another to run a script.
```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.0.dtd" >
<walkmod>

    <plugins>
        <plugin groupId="org.walkmod" artifactId="walkmod-imports-cleaner-plugin" version="2.0" />
    </plugins>

  <chain name="script">
		<reader path="test/classes">
			<include wildcard="**/**"></include>
		</reader>
		<transformation type="walkmod:commons:scripting">
			<param name="language">groovy</param>
			<param name="location">walkmod/script.groovy</param>
		</transformation>
		<writer path="src/main/java" />
	</chain>

    <chain name="clean">
        <reader path="test/classes" />
        <transformation type="walkmod:commons:import-cleaner" />
        <writer path="src/main/java" />
    </chain>

</walkmod>
```

**Test 1: cleaner plugin**
After deleting `.ivy2` from me home folder I run "apply clean -e" and got the same NullPointerException error.
Here is the result: https://gist.github.com/abelsromero/961342c429f9edec1f91

**Test 2: custom script plugin**
After deleting `.ivy2` from me home folder I run "apply script -e" and got the same NullPointerException error.
Here is the result: https://gist.github.com/abelsromero/e6ba6afa5641f728f85c

**Comment by rpau** [comment] 2015-08-26 16:03
Hi Abel,

I have reproduced and identified the problem! :)

It is a bug when the writer path is different than the reader one. The example is not this case, but I promise to solve it ASAP in this week (with its corresponding test).  Probably, there is no test for it and some important changes applied lately have introduced this bug :$

**Comment by abelsromero** [comment] 2015-08-26 16:40
> It is a bug when the writer path is different than the reader one.

How should I set the configuration XML for it to work? Even if the files get overriden it will serve my purpouse.

**Comment by rpau** [comment] 2015-08-26 16:42
Just the reader and the writer path must have the same path.
```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.0.dtd" >
<walkmod>

    <plugins>
        <plugin groupId="org.walkmod" artifactId="walkmod-imports-cleaner-plugin" version="2.0" />
    </plugins>

  <chain name="script">
		<reader path="test/classes">
			<include wildcard="**/**"></include>
		</reader>
		<transformation type="walkmod:commons:scripting">
			<param name="language">groovy</param>
			<param name="location">walkmod/script.groovy</param>
		</transformation>
		<writer path="test/classes" />
	</chain>

    <chain name="clean">
        <reader path="test/classes" />
        <transformation type="walkmod:commons:import-cleaner" />
        <writer path="test/classes" />
    </chain>

</walkmod>
```

**Comment by abelsromero** [comment] 2015-08-26 17:45
Thanks a lot :+1: 
Based on that I have been doing some addional tests (only arround the script case) and found the following:
* Indeed, the output path must be the same as input. This means that either you set the same value or do not set any writer at all. `isMergeable` attribute does not affect at all.
* It is required that all files have some change. If only one file does not change, it fails. Or to put it in another way, when executed twice in a row, the second time it fails.

The error is always the same. I'll look into it a bit more, to see if I can find anything.

**Comment by abelsromero** [comment] 2015-08-26 17:50
Quick correction, when execute twice, the error is different.

**Comment by rpau** [comment] 2015-08-28 08:55
Hi Abel,

It was a bug on the eclipse-formatter-plugin. I have solved it and I have deployed the new version on Maven. 

Try again.

BTW, to use the last version of the declared plugins instead of a fixed one I do:

`````
<plugin groupId="org.walkmod" artifactId="walkmod-imports-cleaner-plugin" version="[2.0.0, 3.0.0)" />
`````

**Comment by abelsromero** [comment] 2015-08-28 10:18
It works but I have found that the files are created adding the source path. ¿Should I update the walkmod installation?

For example, if I have...
```
	<chain name="script">
		<reader path="src/main/java">
        </reader>
		<transformation type="walkmod:commons:scripting" >
			<param name="language">groovy</param>
			<param name="location">walkmod/script.groovy</param>
		</transformation>
        <writer path="src/main/generated" />
	</chain>
```

Files and folders under `src/main/java` are created under `src/main/generated/src/main/java`.

**Comment by abelsromero** [comment] 2015-08-28 11:04
Btw, where's the code? I don't see any changes in the repos. Has it been moved to an organitzation?

**Comment by rpau** [comment] 2015-08-28 11:26
Sorry, I have committed locally, but I haven't pushed the changes.

https://github.com/rpau/walkmod-java-formatter-plugin/blob/master/src/main/java/org/walkmod/javaformatter/writers/EclipseWriter.java

The change is because the AbstractWriter now creates an empty file, and the EclipseWriter checks if the length is 0.

Let me check your example and I send you my feedback.

**Comment by rpau** [comment] 2015-08-28 11:27
BTW: I don't think you need to upgrade the walkmod version, but I will check.

**Comment by abelsromero** [comment] 2015-08-28 11:52
> BTW: I don't think you need to upgrade the walkmod version, but I will check.

There's no need to hurry, take your time. :+1:

**Comment by rpau** [comment] 2015-08-28 13:42
Hi Abel,

I have tested the same example than you using the scripting file of the walkmod webpage and it works. It just creates the generated/package folder. For my (src/main/java/testWalkmod/A.java creates src/main/generaed/testWalkmod/A.java)

So, try to upgrade you walkmod.
Check if both we have the same version of dependencies:

https://gist.github.com/rpau/7d6d9dda918906a40cc5

**Comment by abelsromero** [comment] 2015-08-28 16:55
Fixed! I was my mistake.
Seems my IDE messed with the packages and added `src.main.java` when I moved classes. They had `package src.main.java.cosa;` so they were generated in that path even they were just under `cosa` at the source.

**Closed** 2015-08-28 16:55 UTC
